---
title: "Example Flex Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(readr)
library(dplyr)
library(lubridate)
qc_data <- read_csv("qc_data.csv")
```


Column {data-width=900}
-----------------------------------------------------------------------

### Summary Table

```{r summary}
sum_table <- qc_data %>%
  filter(hospital == "SPH") %>%
  group_by(hospital, test_code, qc_name) %>%
  summarise(obs_mean = round(mean(result),1), obs_sd = round(sd(result),1), obs_cv = round(obs_sd/obs_mean*100, 1), set_mean = round(mean[1],1), set_sd = sd[1], set_cv = round(set_sd/set_mean*100,1))

library(DT)
datatable(sum_table)
```

Column {data-width=600}
-----------------------------------------------------------------------

### LJ PLot 1

```{r ljplotcr1, fig.height=4}
library(lubridate)
library(ggplot2)
library(plotly)

cr_stats<- qc_data %>%
  filter(test_code == "CRQ", hospital == "SPH") %>%
  group_by(qc_name) %>%
  summarise(obs_mean = round(mean(result),1), obs_sd = round(sd(result),1), obs_cv = round(obs_sd/obs_mean*100, 1), set_mean = round(mean[1],1), set_sd = sd[1], set_cv = round(set_sd/set_mean*100,1))

cr1 <- qc_data %>%
  mutate(rundate = date(ymd_hms(date_performed))) %>%
  filter(hospital == "SPH", test_code == "CRQ", qc_name == "CH1") %>%
  group_by(qc_name, rundate) %>% 
  ggplot(aes(x = rundate,y = result)) +
  geom_point(alpha = 0.3, size = 0.5) +
  geom_hline(yintercept = cr_stats$obs_mean[1], col = "blue") + 
  geom_hline(yintercept = cr_stats$obs_mean[1] + 1.96*cr_stats$obs_sd[1], col = "red", linetype = "dashed") + 
  geom_hline(yintercept = cr_stats$obs_mean[1] - 1.96*cr_stats$obs_sd[1], col = "red", linetype = "dashed") + 
  ylim(c(cr_stats$obs_mean[1] - 3*cr_stats$obs_sd[1],cr_stats$obs_mean[1] + 3*cr_stats$obs_sd[1])) +
  ggtitle("Creatinine Level 1") +
  facet_wrap(~instr_code)

ggplotly(cr1)
```

### LJ PLot 2

```{r ljplotcr2, fig.height=4}
cr2 <- qc_data %>%
  mutate(rundate = date(ymd_hms(date_performed))) %>%
  filter(hospital == "SPH", test_code == "CRQ", qc_name == "CH2") %>%
  group_by(qc_name, rundate) %>% 
  ggplot(aes(x = rundate,y = result)) +
  geom_point(alpha = 0.3, size= 0.5) +
  geom_hline(yintercept = cr_stats$obs_mean[2], col = "blue") + 
  geom_hline(yintercept = cr_stats$obs_mean[2] + 1.96*cr_stats$obs_sd[2], col = "red", linetype = "dashed") + 
  geom_hline(yintercept = cr_stats$obs_mean[2] - 1.96*cr_stats$obs_sd[2], col = "red", linetype = "dashed") +
  ylim(c(cr_stats$obs_mean[2] - 3*cr_stats$obs_sd[2],cr_stats$obs_mean[2] + 3*cr_stats$obs_sd[2])) +
  ggtitle("Creatinine Level 2") +
  facet_wrap(~instr_code)

ggplotly(cr2)
```
